package LogicModule;

import java.util.ArrayList;

public class Order {

	private int orderID;
	private int tableID;
	private int waiterID;
	private ArrayList<OrderLineItem> lineItemList = new ArrayList<OrderLineItem>();
	private boolean isComplete = false;
	
	/**
	 * 
	 * @param orderID The orderID in system memory, should be automated generated by system.
	 * @param TableID The table ID of this order.
	 * @param waiterID The waiter ID of waiter who placed this order.
	 */
	public Order(int orderID, int TableID, int waiterID) {
		// TODO Auto-generated constructor stub
		this.orderID = orderID;
		this.tableID = TableID;
		this.waiterID = waiterID;
	}
	
	/**
	 * change order status from incomplete to complete
	 */
	public void orderComplete(){
		this.isComplete = true;
	}
	
	/**
	 * insert new Line Item to this order.
	 * @param itemName The item name.
	 * @param quantity The item quantity.
	 */
	public void insertLineItem(String itemName, int quantity){
		OrderLineItem olt = new OrderLineItem(itemName, quantity);
		lineItemList.add(olt);
	}
	
	public int getOrderID() {
		return orderID;
	}

	public int getTableID() {
		return tableID;
	}
	
	public int getWaiterID() {
		return waiterID;
	}

	public ArrayList<OrderLineItem> getLineItemList() {
		return lineItemList;
	}

	public void setLineItemList(ArrayList<OrderLineItem> lineItemList) {
		this.lineItemList = lineItemList;
	}
}
